<header>
    <h1>RC IT Solutions</h1>
    <img src="images/RC2.png" alt="RC" id="banner">
    <nav id="navbar">
        <a href="index.php" id="index" >Home</a>
        <a href="jobs.php" id="jobslink" >Jobs</a>
        <a href="apply.php" id="apply" >Apply</a>
        <a href="about.php" id="about" >About</a>
        <a href="enhancements.php" id="enhancements" >Enhancements</a>
        <a href="enhancements2.php" id="jsenhancements" >JS Enhancements</a>
        <a href="manage.php" id="manage">Manage</a>
    </nav>
</header>